# Generated by Django 5.0.1 on 2024-01-09 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AndroidAppModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=400)),
                ("app_link", models.URLField(max_length=1000)),
                (
                    "app_category",
                    models.CharField(
                        choices=[
                            ("Entertainment", "Entertainment"),
                            ("Education", "Education"),
                            ("Lifestyle", "Lifestyle"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "app_sub_category",
                    models.CharField(
                        choices=[
                            ("Social Media", "Social Media"),
                            ("Blog", "Blog"),
                            ("Live Streaming", "Live Streaming"),
                        ],
                        max_length=100,
                    ),
                ),
                ("points", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                ("username", models.CharField(max_length=300)),
                ("user_email", models.EmailField(max_length=100)),
                ("user_points", models.IntegerField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_img", models.ImageField(upload_to="tasks/")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_app",
                        to="taskTrackingApp.androidappmodel",
                    ),
                ),
            ],
        ),
    ]
